name: build

defaults:
  run:
    working-directory: WinNUT_V2

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main, Dev-2.2 ] # Build for dev primarily, probably don't need main...?
    paths:
    - '**.vb'
    - '**.vbproj'

env:
  DOTNET_VERSION: '4.7.2' # The .NET SDK version to use
  SLN_FILE: WinNUT_V2.sln
  BUILD_NUM:

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] # Should have MSBuild.
    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout Code
      uses: actions/checkout@v3

      # Calculate the build number. Will change to a new strategy after the next minor release.
    - name: Calculate Version
      run: |
        Write-Output "::echo::on"
        ([int]$env:GITHUB_RUN_NUMBER + 8303) >> $env:BUILD_NUM
        echo "Set Build version to $env:BUILD_NUM"

    - name: (Debug) Output ENV vars
      run: env

    - name: Restore Packages
      run: msbuild -t:restore

    # msbuild cannot handle .vdproj Installer projects, so only build debug for now.
    - name: Build solution
      run: |
        Write-Output "::echo::on"
        msbuild $env:SLN_FILE -p:Configuration=Debug -p:AssemblyFileVersion=2.2.$env:BUILD_NUM

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('WinNUT-Client-debugbuild-v2.2.{0}', env.BUILD_NUM) }}
        if-no-files-found: error
        path: |
          WinNUT_V2/WinNUT-Client/bin/Debug
          
