name: build

defaults:
  run:
    working-directory: WinNUT_V2

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main, Dev-2.2 ] # Build for dev primarily, probably don't need main...?
    paths:
    - '**.vb'
    - '**.vbproj'

env:
  DOTNET_VERSION: '4.7.2' # The .NET SDK version to use
  SLN_FILE: WinNUT_V2.sln

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] # Should have MSBuild.
    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Setup Nuget
    #   uses: nuget/setup-nuget@v1
    
    # - name: Restore NuGet Packages
    #   run: nuget restore $env:SLN_FILE  
    - name: Restore Packages
      run: msbuild -t:restore

    # msbuild cannot handle .vdproj Installer projects, so only build debug for now.
    - name: Build solution
      run: msbuild $env:SLN_FILE /p:Configuration=Debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-winnut
        if-no-files-found: error
        path: |
          WinNUT_GUI/bin/Debug
          
