name: build

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main, Dev-2.2 ] # Build for dev primarily, probably don't need main...?
    paths:
    - '**.vb'
    - '**.vbproj'

env:
  DOTNET_VERSION: '4.7.2' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # Only building for Windows. Should have MSBuild.
    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.2
      env:
        # ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    - name: Restore NuGet Packages
      run: nuget restore WinNUT_V2/WinNUT_V2.sln     

    - name: Build solution
      run: msbuild WinNUT_V2/WinNUT_V2.sln /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-winnut
        if-no-files-found: error
        path: |
          WinNUT_V2/WinNUT_GUI/bin/Release
          WinNUT_V2/Setup/Release
