name: build

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main, Dev-2.2 ] # Build for dev primarily, probably don't need main...?
    paths:
    - '**.vb'
    - '**.vbproj'

env:
  DOTNET_VERSION: '4.7.2' # The .NET SDK version to use
  # Below is copied from https://github.com/actions/runner-images/issues/128#issuecomment-565227772
  # and https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
  DEV_EXE: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com"
  SLN_PATH: WinNUT_V2/WinNUT_V2.sln

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] # Only building for Windows, set to our current development environment.
    steps:
    # Make devenv available so .vdproj can be built.
    # - name: Setup devenv
    #   uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
    
    - name: Restore NuGet Packages
      run: nuget restore "%SLN_PATH"  

    - name: Build solution
      run: "%DEV_EXE" "%SLN_PATH" /build release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-winnut
        if-no-files-found: error
        path: |
          WinNUT_V2/WinNUT_GUI/bin/Release
          WinNUT_V2/Setup/Release
