name: build

defaults:
  run:
    working-directory: WinNUT_V2

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ main, Dev-2.2 ] # Build for dev primarily, probably don't need main...?
    paths:
    - '**.vb'
    - '**.vbproj'

env:
  DOTNET_VERSION: '4.7.2' # The .NET SDK version to use
  SLN_FILE: WinNUT_V2.sln
  DEBUG_OUTPUT: WinNUT_V2/WinNUT-Client/bin/Debug

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019] # Should have MSBuild.
    steps:
    # Make MSBuild available from $PATH.
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Checkout Code
      uses: actions/checkout@v3

      # Calculate the build number. Will change to a new strategy after the next minor release.
    # - name: Calculate Version
    #   run: |
    #     Write-Output "::echo::on"
    #     $calcBuildNum = ([int]$env:GITHUB_RUN_NUMBER + 8303)
    #     echo "Calculated number $calcBuildNum"
    #     echo "BUILD_NUM=$calcBuildNum" | Out-File -FilePath $env:GITHUB_ENV -Append
    #     echo "Set Build version to $env:BUILD_NUM"

    # - name: (Debug) Output ENV vars
    #   run: env

    - name: Restore Packages
      run: msbuild -t:restore

    # msbuild cannot handle .vdproj Installer projects, so only build debug for now.
    - name: Build solution
      run: |
        Write-Output "::echo::on"
        msbuild.exe $env:SLN_FILE -p:Configuration=Debug -p:AssemblyFileVersion=2.2.$env:BUILD_NUM

    - name: Get AssemblyVersion generated by msbuild
      id: getversion
      uses: berglie/assembly-version/get@v1
      with:
        directory: `

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('WinNUT-Client-debugbuild-v2.2.{0}', steps.getversion.outputs.version) }}
        if-no-files-found: error
        path: |
          env.DEBUG_OUTPUT
          
